version = 0.1

[default.deploy.parameters]
stack_name = "thaam"
resolve_s3 = true
s3_prefix = "thaam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ScreenshotRetentionDays=\"7\" CasePackRetentionDays=\"90\" AllowedOrigin=\"https://main.dhg3lzpzbimpz.amplifyapp.com\" DevOrigin=\"http://localhost:5173\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
